import type { Metadata } from 'next'
import { Inter, IBM_Plex_Mono } from 'next/font/google'
import './globals.css'
import ConvexClientProvider from './ConvexClientProvider'

const inter = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: [`100`, `200`, `300`, `400`, `500`, `600`, `700`]
})

export const metadata: Metadata = {
  title: 'Next XL-AI Adventure',
  description: 'Generated by Arik Alexandrov',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  )
}
