import type { Metadata } from 'next'
import { Inter, Eagle_Lake } from 'next/font/google'
import './globals.css'
import ConvexClientProvider from './ConvexClientProvider'

const inter = Eagle_Lake({
  subsets: ['latin'],
  weight:['400']
})

export const metadata: Metadata = {
  title: 'Next XL-AI Adventure',
  description: 'Generated by Arik Alexandrov',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  )
}
